import Moralis from 'moralis'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({address, nativeBalance}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        El saldo en ether de {address} es {nativeBalance}

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(context) {
  await Moralis.start({ apiKey: process.env.MORALIS_API_KEY });
  const address = '0x73c94f5735Ea62447ee51cF69eEc02cc19497be3';
  const nativeBalance = await Moralis.EvmApi.account.getNativeBalance({
      address,
      chain: 42,
  });
  console.log("running on server side!!!")
  return {
      props: { address, nativeBalance: nativeBalance.result.balance.ether,  },
  };
}
